name: New Disc
description: Submit a new disc that is not already in the project
labels: ["newdisc"]
assignees: ["intothisworld"]
title: "[NEW] PLACEHOLDER NAME"
body:
  # Common Disc Info
  - type: markdown
    attributes:
      value: "## Common Disc Info"
  - type: dropdown
    id: d_system
    attributes:
      label: System
      options:
        - Apple Macintosh
        - Embedded Systems
        - IBM PC Compatible
        - Media - Audiobooks
        - Media - Films
        - Media - Music
        - Media - Television
        - Miscellaneous
    validations:
      required: true
  - type: dropdown
    id: d_media
    attributes:
      label: Media
      options:
        - CD-ROM
        - CD-ROM - Audio CD
        - CD-ROM - CD+G
        - CD-ROM - Enhanced CD
        - CD-ROM - HDCD
        - CD-ROM - Movie CD
        - CD-ROM - MP3 CD
        - CD-ROM - Video CD
        - BD-ROM
        - BD-ROM - BD-Video
        - DVD-ROM
        - DVD-ROM - DVD-Audio
        - DVD-ROM - DVD-Video
        - HD-DVD
        - Playbutton
        - SACD
        - Other (Specify in comments)
    validations:
      required: true
  - type: input
    id: d_title
    attributes:
      label: Title
    validations:
      required: true
  - type: input
    id: d_title_foreign
    attributes:
      label: Foreign Title (Non-Latin)
  - type: input
    id: d_number
    attributes:
      label: Disc Number/Letter
  - type: input
    id: d_label
    attributes:
      label: Disc Title
  - type: dropdown
    id: d_category
    attributes:
      label: Category
      options:
        - Anime
        - Audiobooks
        - Comedy
        - Device Drivers & Utilities
        - Documentaries
        - Documentaries - Conspiracy
        - Educational
        - General
        - Instructional
        - Karaoke
        - Multimedia
        - Operating Systems
        - Promotional
        - Software - Applications
        - Software - Coverdiscs
        - Soundtracks
        - Soundtracks - Anime
        - Soundtracks - Anime - Unofficial
        - Soundtracks - Film
        - Soundtracks - Game - Unofficial
        - Soundtracks - Television
    validations:
      required: true
  - type: checkboxes
    id: d_region
    attributes:
      label: Region
      options:
        - label: Afghanistan
        - label: Aland Islands
        - label: Albania
        - label: Algeria
        - label: American Samoa
        - label: Andorra
        - label: Angola
        - label: Anguilla
        - label: Antarctica
        - label: Antigua and Barbuda
        - label: Argentina
        - label: Armenia
        - label: Aruba
        - label: Ascension Island
        - label: Asia
        - label: Australia
        - label: Austria
        - label: Azerbaijan
        - label: Bahamas
        - label: Bahrain
        - label: Bangladesh
        - label: Barbados
        - label: Belarus
        - label: Belgium
        - label: Belize
        - label: Benin
        - label: Bermuda
        - label: Bhutan
        - label: Bolivia
        - label: Bonaire
        - label: Bosnia and Herzegovina
        - label: Botswana
        - label: Bouvet Island
        - label: Brazil
        - label: British Indian Ocean Territory
        - label: Brunei Darussalam
        - label: Bulgaria
        - label: Burkina Faso
        - label: Burundi
        - label: Cabo Verde
        - label: Cambodia
        - label: Cameroon
        - label: Canada
        - label: Canary Islands
        - label: Cayman Islands
        - label: Central African Republic
        - label: Ceuta Melilla
        - label: Chad
        - label: Chile
        - label: China
        - label: Christmas Island
        - label: Clipperton Island
        - label: Cocos Islands
        - label: Colombia
        - label: Comoros
        - label: Congo
        - label: Cook Islands
        - label: Costa Rica
        - label: Cote d' Ivoire
        - label: Croatia
        - label: Cuba
        - label: Curacao
        - label: Cyprus
        - label: Czechia
        - label: Czechoslovakia
        - label: Democratic Republic of the Congo
        - label: Denmark
        - label: Diego Garcia
        - label: Djibouti
        - label: Dominica
        - label: Dominican Republic
        - label: Ecuador
        - label: Egypt
        - label: El Salvador
        - label: Equatorial Guinea
        - label: Eritrea
        - label: Estonia
        - label: Eswatini
        - label: Ethiopia
        - label: Europe
        - label: Falkland Islands
        - label: Faroe Islands
        - label: Federated States of Micronesia
        - label: Fiji
        - label: Finland
        - label: France
        - label: French Guiana
        - label: French Polynesia
        - label: French Southern Territories
        - label: Gabon
        - label: Gambia
        - label: Georgia
        - label: Germany
        - label: Ghana
        - label: Gibraltar
        - label: Greater China
        - label: Greece
        - label: Greenland
        - label: Grenada
        - label: Guadeloupe
        - label: Guam
        - label: Guatemala
        - label: Guernsey
        - label: Guinea
        - label: Guinea Bissau
        - label: Guyana
        - label: Haiti
        - label: Heard Island and McDonald Islands
        - label: Holy See
        - label: Honduras
        - label: Hong Kong
        - label: Hungary
        - label: Iceland
        - label: India
        - label: Indonesia
        - label: Iran
        - label: Iraq
        - label: Ireland
        - label: Island of Sark
        - label: Isle of Man
        - label: Israel
        - label: Italy
        - label: Jamaica
        - label: Japan
        - label: Jersey
        - label: Jordan
        - label: Kazakhstan
        - label: Kenya
        - label: Kiribati
        - label: North Korea
        - label: South Korea
        - label: Kuwait
        - label: Kyrgyzstan
        - label: Laos
        - label: Latin America
        - label: Latvia
        - label: Lebanon
        - label: Lesotho
        - label: Liberia
        - label: Libya
        - label: Liechtenstein
        - label: Lithuania
        - label: Luxembourg
        - label: Macao
        - label: Madagascar
        - label: Malawi
        - label: Malaysia
        - label: Maldives
        - label: Mali
        - label: Malta
        - label: Marshal lIslands
        - label: Martinique
        - label: Mauritania
        - label: Mauritius
        - label: Mayotte
        - label: Mexico
        - label: Monaco
        - label: Mongolia
        - label: Montenegro
        - label: Montserrat
        - label: Morocco
        - label: Mozambique
        - label: Myanmar
        - label: Namibia
        - label: Nauru
        - label: Nepal
        - label: Netherlands
        - label: Netherlands Antilles
        - label: New Caledonia
        - label: New Zealand
        - label: Nicaragua
        - label: Niger
        - label: Nigeria
        - label: Niue
        - label: Norfolk Island
        - label: North Macedonia
        - label: Northern Mariana Islands
        - label: Norway
        - label: Oman
        - label: Pakistan
        - label: Palau
        - label: Panama
        - label: Papua New Guinea
        - label: Paraguay
        - label: Peru
        - label: Philippines
        - label: Pitcairn
        - label: Poland
        - label: Portugal
        - label: Puerto Rico
        - label: Qatar
        - label: Republic of Moldova
        - label: Reunion
        - label: Romania
        - label: Russian Federation
        - label: Rwanda
        - label: Saint Barthelemy
        - label: Saint Helena
        - label: Saint Kitts and Nevis
        - label: Saint Lucia
        - label: Saint Martin
        - label: Saint Pierre and Miquelon
        - label: Saint Vincent and the Grenadines
        - label: Samoa
        - label: San Marino
        - label: Sao Tome and Principe
        - label: Saudi Arabia
        - label: Scandinavia
        - label: Senegal
        - label: Serbia
        - label: Seychelles
        - label: Sierra Leone
        - label: Singapore
        - label: Sint Maarten
        - label: Slovakia
        - label: Slovenia
        - label: Solomon Islands
        - label: Somalia
        - label: South Africa
        - label: South Georgia
        - label: South Sudan
        - label: Spain
        - label: Sri Lanka
        - label: State of Palestine
        - label: Sudan
        - label: Suriname
        - label: Svalbard and Jan Mayen
        - label: Sweden
        - label: Switzerland
        - label: Syrian Arab Republic
        - label: Taiwan
        - label: Tajikistan
        - label: Thailand
        - label: Timor Leste
        - label: Togo
        - label: Tokelau
        - label: Tonga
        - label: Trinidad and Tobago
        - label: Tristan da Cunha
        - label: Tunisia
        - label: Turkey
        - label: Turkmenistan
        - label: Turks and Caicos Islands
        - label: Tuvalu
        - label: Uganda
        - label: United Kingdom
        - label: Ukraine
        - label: United Arab Emirates
        - label: United Republic of Tanzania
        - label: United States Minor Outlying Islands
        - label: Uruguay
        - label: United States of America
        - label: USSR
        - label: Uzbekistan
        - label: Vanuatu
        - label: Venezuela
        - label: VietNam
        - label: British Virgin Islands
        - label: US Virgin Islands
        - label: Wallis and Futuna
        - label: Western Sahara
        - label: World
        - label: Yemen
        - label: Yugoslavia
        - label: Zambia
        - label: Zimbabwe
  - type: input
    id: d_languages # Make into `checkboxes`
    attributes:
      label: Languages
  # Skip d_languages_selection - PSX/PS2 only
  - type: input
    id: d_serial
    attributes:
      label: Serial
  - type: input
    id: d_barcode
    attributes:
      label: Barcode
  - type: input
    id: d_date
    attributes:
      label: EXE Date (yyyy-MM-dd)
  - type: input
    id: d_errors
    attributes:
      label: Errors Count
    validations:
      required: true
  - type: textarea
    id: d_comments
    attributes:
      label: Comments
  - type: textarea
    id: d_contents
    attributes:
      label: Contents

  - type: markdown
    attributes:
      value: "## Ringcode Information"
  # Skip d_ring - Unused in submission form
  # Skip d_ring_0_id - Unused in submission form

  - type: markdown
    attributes:
      value: "### Layer 0 / Data Side"
  - type: input
    id: d_ring_0_ma1
    attributes:
      label: Mastering Ring
  - type: input
    id: d_ring_0_ma1_sid
    attributes:
      label: Mastering SID
  - type: input
    id: d_ring_0_ts1
    attributes:
      label: Mastering Code
  - type: input
    id: d_ring_0_mo1_sid
    attributes:
      label: Mould SID
  - type: input
    id: d_ring_0_mo1
    attributes:
      label: Additional Mould

  - type: markdown
    attributes:
      value: "### Layer 1 / Label Side"
  - type: input
    id: d_ring_0_ma2
    attributes:
      label: Mastering Ring
  - type: input
    id: d_ring_0_ma2_sid
    attributes:
      label: Mastering SID
  - type: input
    id: d_ring_0_ts2
    attributes:
      label: Mastering Code
  - type: input
    id: d_ring_0_mo2_sid
    attributes:
      label: Mould SID
  - type: input
    id: d_ring_0_mo2
    attributes:
      label: Additional Mould

  - type: markdown
    attributes:
      value: "### Layer 2"
  - type: input
    id: d_ring_0_ma3
    attributes:
      label: Mastering Ring
  - type: input
    id: d_ring_0_ma3_sid
    attributes:
      label: Mastering SID
  - type: input
    id: d_ring_0_ts3
    attributes:
      label: Mastering Code

  - type: markdown
    attributes:
      value: "### Layer 3"
  - type: input
    id: d_ring_0_ma4
    attributes:
      label: Mastering Ring
  - type: input
    id: d_ring_0_ma4_sid
    attributes:
      label: Mastering SID
  - type: input
    id: d_ring_0_ts4
    attributes:
      label: Mastering Code

  # Skip d_ring_0_offsets - Unused in submission form
  # Skip d_ring_0_0_id - Unused in submission form
  # Skip d_ring_0_0_density - Unused in submission form
  # Skip d_ring_0_0_value - Unused in submission form
  # Skip d_ring_count - Unused in submission form

  # Version and Editions
  - type: markdown
    attributes:
      value: "## Version and Editions"
  - type: input
    id: d_version
    attributes:
      label: Version
  - type: input
    id: d_editions
    attributes:
      label: Edition

  # EDC
  # Skip d_edc - PSX only

  # Parent/Clone Relationship
  - type: markdown
    attributes:
      value: "## Parent/Clone Relationship"
  - type: input
    id: d_parent_id
    attributes:
      label: Parent ID
  # Skip d_is_regional_parent - Unused in submission form

  # Extras
  - type: markdown
    attributes:
      value: "## Extras"
  - type: textarea
    id: d_pvd
    attributes:
      label: Primary Volume Descriptor (PVD) (ISO9660 FS only)
  # Skip d_d1_key - Systems with keys only
  # Skip d_d2_key - Systems with keys only
  - type: textarea
    id: d_pic_data
    attributes:
      label: Permanent Information & Control (PIC)
  - type: textarea
    id: d_header
    attributes:
      label: Header
  # Skip d_ssranges - XGD only

  # Copy Protection
  - type: markdown
    attributes:
      value: "## Copy Protection"
  # Skip d_protection_a - PSX/PS2 only
  # Skip d_protection_1 - PSX/PS2 only
  # Skip d_libcrypt - PSX/PS2 only
  - type: textarea
    id: d_protection
    attributes:
      label: Protection
  - type: textarea
    id: d_securom
    attributes:
      label: SecuROM Data

  # Dumpers and Status
  # Skip d_status - Unused in submission form
  # Skip d_dumpers - Unused in submission form
  # Skip d_dumpers_text - Unused in submission form

  # Tracks and Write Offsets
  - type: markdown
    attributes:
      value: "## Tracks and Write Offsets (CD only)"
  - type: textarea
    id: d_tracks
    attributes:
      label: ClrMamePro Data (Track Hashes)
  - type: textarea
    id: d_cue
    attributes:
      label: Cuesheet
  # Skip d_offset - Unused in submission form
  - type: input
    id: d_offset_text
    attributes:
      label: Write Offset

  # Tracks and Write Offsets
  - type: markdown
    attributes:
      value: "## Sizes and Checksums (DVD, HD-DVD, BD, SACD)"
  - type: input
    id: d_layerbreak
    attributes:
      label: Layerbreak 1
  - type: input
    id: d_layerbreak_2
    attributes:
      label: Layerbreak 2
  - type: input
    id: d_layerbreak_3
    attributes:
      label: Layerbreak 3
  - type: textarea
    id: d_pic_identifier
    attributes:
      label: Permanent Information & Control (PIC)
  - type: input
    id: d_size
    attributes:
      label: Size
  - type: input
    id: d_crc32
    attributes:
      label: CRC-32
  - type: input
    id: d_md5
    attributes:
      label: MD5
  - type: input
    id: d_sha1
    attributes:
      label: SHA-1

  # Dumping Info
  - type: markdown
    attributes:
      value: "## Dumping Info"
  - type: textarea
    id: Dumping_Info
    attributes:
      label: Dumping Info
      description: Full contents of the dumping info section